config/routes.rb
ActionController::Routing::Routes.draw do |map|

  # FRONT END                 
  map.search '/search/:search', :controller => 'search', :action => 'index'
  map.search '/search', :controller => 'search', :action => 'index'

  map.resources :tags, :only => [:show]
  map.resources :pages, :only => [:show]
  map.resources :articles, :only => [:show,:index], :collection => { 'archives' => :get }
  map.resources :comments, :only => [:index,:create]
  map.resources :categories, :only => [:index,:show]
  
  # Restful Authentication Resources
  map.resources :users
  map.resources :passwords
  map.resource :session

  map.namespace :admin do |admin|            
    admin.resources :menu_items
    admin.resources :menus
    admin.resources :tags
    admin.resources :permissions
    admin.resources :roles_permissions
    admin.resources :users
    admin.resources :roles
    admin.resources :pages, :member => "revert_to_previous"
    admin.resources :articles, :member => "revert_to_previous"
    admin.resources :comments 
    admin.resources :links     
    admin.resources :categories    
    admin.resources :content_areas  
    admin.resources :content_blocks  
    admin.resources :preferences, :collection => { :adjust => :put }   
    admin.resources :assets, :collection => { 'file_browser' => [:get,:post], 'gallery'=>[:get] }    
  end

  # ADMIN
  map.connect '/admin/', :controller => 'admin/admin', :action => 'dashboard'
  map.dashboard '/admin/dashboard', :controller => 'admin/admin', :action => 'dashboard'

  # Restful Authentication Rewrites
  map.logout '/logout', :controller => 'sessions', :action => 'destroy'
  map.login '/login', :controller => 'sessions', :action => 'new'
  map.register '/register', :controller => 'users', :action => 'create'
  map.signup '/signup', :controller => 'users', :action => 'new'
  map.activate '/activate/:activation_code', :controller => 'users', :action => 'activate', :activation_code => nil
  map.forgot_password '/forgot_password', :controller => 'passwords', :action => 'new'
  map.change_password '/change_password/:reset_code', :controller => 'passwords', :action => 'reset'
  map.open_id_complete '/opensession', :controller => "sessions", :action => "create", :requirements => { :method => :get }
  map.open_id_create '/opencreate', :controller => "users", :action => "create", :requirements => { :method => :get }
    
  # Home Page
  map.root :controller => 'articles', :action => 'index'

  map.connect 'articles/:year/:month/',
                :controller => 'articles',
                :action     => 'find_by_date',
                :year       => /\d{4}/,
                :month      => /\d{1,2}/


  map.connect ':id', :controller => 'pages', :action => 'show'

  # Install the default routes as the lowest priority.
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'

end

app/models/role.rb
class Role < ActiveRecord::Base
  default_scope :order => 'name ASC'  
  has_and_belongs_to_many :users
  has_many :roles_permissions
  has_many :permissions, :through => :roles_permissions
  class << self
    attr_accessor :omit_fields, :search_fields, :filter_options, :association_fields, :custom_views; 
  end
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < Admin::AdminController      
  
  def edit
    @role = Role.find(params[:id])
    render :template => 'admin/wilderness/pages/edit'
  end
  
  
end

app/views/admin/roles/_form.html.erb
<% form_for [:admin, @item] do |f| %>
	<% error_messages_for :role %>
	<%= f.label :name %>
	<%= f.text_field :name %>       

	<h2>Permissions</h2> 
 <div class='checkbox-group'>
		<% Permission.all.each do |permission| -%>
			<%= check_box_tag 'role[permission_ids][]', permission.id, @item.permissions.include?(permission), :id => permission.title %> 
			<label for='<%= permission.title %>'><%= permission.title %><label>
				<br />
	<% end -%>
	</div> 
	
	<%= f.submit :Go %>
<% end %>

app/views/admin/roles/show.html.erb
<%= header(@klass) %>

<dl id='<%= @klass.to_s.downcase %>_<%= @item.id %>'>

	<dt>Role</dt>
	<dd><%= @item.name %></dd>
  
	<dt>Edit</dt>
	<dd><%= link_to image_tag('icons/pencil.png'), edit_admin_role_path(@item) %></th>

	<dt>Delete</dt>
	<dd><%= link_to image_tag('icons/delete.png'), [:admin,@item], :method => :delete, :confirm => 'Are you sure' %></dd>                              

</dl>

<%= render :partial => 'admin/users/table', :locals => { :items => @item.users } %>